version: '3.6'
services:
  sf-node:
    image: 'functionland/sugarfunge-node:latest'
    restart: always
    network_mode: "host"
    command: ["--pruning=archive", "--chain=./customSpecRaw.json", "--name=fula-docker", "--execution=wasm", "--port=30334", "--ws-port", "9944", "--ws-external", "--rpc-external", "--rpc-cors", "all", "--bootnodes", "/dns4/node.testnet.fx.land/tcp/30334/p2p/12D3KooWJWmLsCgqubfTLcscgJpovaZTWJD7c8XUXE8w4yYYUMwK"]
    volumes:
      - ./data/fula-docker:/root/.local/share/sugarfunge-node/chains/live_testnet
      - ./customSpecRaw.json:/customSpecRaw.json
  sf-api:
    image: 'functionland/sugarfunge-api:latest'
    restart: always
    network_mode: "host"
    command: ["-l", "http://0.0.0.0:4000", "-s", "ws://127.0.0.1:9944"]
  ipfs:
    container_name: ipfs
    image: 'ipfs/go-ipfs:v0.13.0'
    entrypoint: ["sh", "/scripts/ipfs-setup.sh"]
    restart: always
    ports:
      - "4001:4001"
      - "8001:8080"
      - "5001:5001"
    volumes:
      - ./scripts/ipfs-setup.sh:/scripts/ipfs-setup.sh
      - ./ipfs:/data/ipfs
      - ./swarm.key:/data/ipfs/swarm.key
  proof-engine:
    image: 'functionland/proof-engine:latest'
    restart: always
    network_mode: "host"
    environment:
      RUST_LOG: 'warn,proof_engine=info'
  box:
    container_name: box
    image: functionland/box:v0.6.5
    restart: unless-stopped
    depends_on:
      - ipfs
      - cluster
    volumes:
      - ./data/box:/opt/apps/box/data
    environment:
      DEBUG: "box:*"
      NODE_ENV: "production"
      FULA_CLUSTER_PROXY: "http://cluster:9095"
      FULA_IPFS_HTTP: "http://ipfs:5001"
    ports:
      - "4002:4002"
      - "4003:4003"
  cluster:
    container_name: cluster
    image: functionland/ipfs-cluster:v1.0.1
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      # Open API port (allows ipfs-cluster-ctl usage on host)
      - "127.0.0.1:9094:9094"
      - "9095:9095"
    volumes:
      - ./data/cluster:/data/ipfs-cluster
